<?php

/**
 * @file
 * Examples showing how to use some of the new JavaScript features in Drupal 7.
 */

/**
 * Implements hook_libraries_info().
 *
 * For defining external libraries.
 */
function thailand_address_libraries_info() {

  // A very simple library. No changing APIs (hence, no versions), no variants.
  // Expected to be extracted into 'sites/all/libraries/simple'.
  $libraries['thailand_address'] = array(
    'name' => 'jquery.Thailand.js',
    'vendor url' => 'https://github.com/earthchie/jquery.Thailand.js',
    'download url' => 'https://github.com/earthchie/jquery.Thailand.js/archive/master.zip',
    'version arguments' => array(
      'file' => 'jquery.Thailand.js/src/jquery.Thailand.js', // Could be any file with version info 
      'pattern' => '@version\s+([0-9a-zA-Z\.-]+)@', 
      'lines' => 3,
    ),
    'files' => array(
      'js' => array('jquery.Thailand.js/src/jquery.Thailand.js'), //this can be a path to the file location like array('lib/simple.js')
    ),
  );

  return $libraries;
}

/**
 * Implements hook_form_alter().
 *
 * This config  Disabled/ Enabled module 'Thailand address'. 
 * 
 */
function thailand_address_form_alter(&$form, $form_state, $form_id) {
  // First, check for the node type configuration form.
  if ($form_id == 'node_type_form') {
    $form['thailand_address'] = array(
      '#type' => 'fieldset',
      '#title' => t('Thailand Address settings'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#group' => 'additional_settings',
      '#weight' => -1,
    );

    $form['thailand_address']['thailand_address_node_type'] = array(
      '#type' => 'radios',
      '#title' => t('Thailand Address Use:'),
      '#default_value' => variable_get('thailand_address_node_type_' . $form['#node_type']->type, FALSE),
      '#options' => array(
        FALSE => t('Disabled'),
        TRUE => t('Enabled'),
      ),
      '#description' => t('Should this node have a Thailand Address Module.'),
    );
  }
  // Here we check to see if the type and node field are set. If so, it could
  elseif (isset($form['type']) && isset($form['#node']) && $form['type']['#value'] . '_node_form' == $form_id) {
    // into the form.
    $node = $form['#node'];
    if (variable_get('thailand_address_node_type_' . $form['type']['#value'], FALSE)) {

    }
  }
}